import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DesktopNavbar from "@/components/desktopNavbar";
import Navbar from "@/components/navbar";
import NavbarContainer from "@/components/NavbarContainer";
import Providers from "./providers";
import { Toaster } from "@/components/ui/toaster";
import { Nunito, Oswald } from "next/font/google";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// const nunito = Nunito({
  
//   subsets: ["latin"],
// });

const oswald = Oswald({
subsets:["latin"],
display:"block"

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.className} antialiased`}>
        <Providers>
          <NavbarContainer>
            <Navbar />
          </NavbarContainer>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
